mainnet_v1: Add COOP into bridged-token-list
nervosnetwork/godwoken-info pull request #42
Opened 2022-06-30 16:31 UTC by jjyr

Add COOP

2022-06-30 17:32 UTC, Keith-CY commented
cc @zmcNotafraid

2022-07-01 01:08 UTC, Flouse requested changes

2022-07-01 01:08 UTC, Flouse commented on mainnet_v1/bridged-token-list.json
> +    }
```suggestion
    },
    "UAN": "COOP.ckb",
    "displayName": "COOP (from CKB)"
```

2022-07-01 02:01 UTC, Flouse commented on mainnet_v1/bridged-token-list.json
> +    }
gw: Godwoken
gb: Godwoken Bridge

2022-07-01 04:07 UTC, Flouse approved these changes

2022-07-01 04:08 UTC, merged