testnet_v1: bump godwoken-prebuilds to 1.7.1-poly1.5.0
nervosnetwork/godwoken-info pull request #77
Opened 2022-11-13 06:03 UTC by Flouse

## Noteable Changes
1. Fix partial state revert logic in https://github.com/godwokenrises/godwoken-polyjuice/pull/184
   fix: Support revert inner call state https://github.com/godwokenrises/godwoken/pull/835
    
2. fork(consensus): Increase l2 tx max cycles from 150M to 500M
    https://github.com/godwokenrises/godwoken/pull/852
3. https://github.com/godwokenrises/godwoken-polyjuice/pull/88

## Release notes
- Godwoken 
   https://github.com/godwokenrises/godwoken/releases/tag/v1.7.1

- [Release Polyjuice 1.4.6 and 1.5.0· godwokenrises/godwoken-polyjuice]
   - https://github.com/godwokenrises/godwoken-polyjuice/releases/tag/1.4.6
   - https://github.com/godwokenrises/godwoken-polyjuice/releases/tag/1.5.0

## Changed Configs
1. [increase_max_l2_tx_cycles_to_500m at testnet_v1_block#825000](https://github.com/godwokenrises/godwoken-info/compare/testnet_v1?expand=1#diff-7e686c21daa843938ca4c0df5db2fe3b79bdb6e1845d19659f941f0a811e0976R15)
2. [add [[fork.backend_forks.backends.Polyjuice1.5.0]]](https://github.com/godwokenrises/godwoken-info/compare/testnet_v1?expand=1#diff-7e686c21daa843938ca4c0df5db2fe3b79bdb6e1845d19659f941f0a811e0976R17-R83)

2022-11-14 02:24 UTC, jjyr requested changes

2022-11-14 02:24 UTC, jjyr commented on testnet_v1_1/gw-testnet_v1-config-readonly.toml
>  execute_l2tx_max_cycles = 100000000
```suggestion
execute_l2tx_max_cycles = 500000000
```

2022-11-14 04:03 UTC, ShiningRay approved these changes

2022-11-14 04:27 UTC, merged

2022-11-15 03:35 UTC, Flouse commented
> 2\. [add [[fork.backend_forks.backends.Polyjuice1.5.0]]](https://github.com/godwokenrises/godwoken-info/compare/testnet_v1?expand=1#diff-7e686c21daa843938ca4c0df5db2fe3b79bdb6e1845d19659f941f0a811e0976R17-R83) at testnet_v1_block#825000

Godwoken testnet_v1 has been upgraded to Godwoken 1.7.1 and Polyjuice 1.5.0.