testnet_v1: bump to Godwoken v1.12-rc-smt-trie and Web3/Indexer 1.12-rc
nervosnetwork/godwoken-info pull request #88
Opened 2023-02-21 08:59 UTC by Simon-Tl

## Notable Changes
- Highlights
   - Builtin mainnet and testnet consensus config https://github.com/godwokenrises/godwoken/pull/946
   - Add web3 and web3-indexer into the monorepo https://github.com/godwokenrises/godwoken/pull/910

- Bug fixes:

   - gwos-evm: fix big mod exp https://github.com/godwokenrises/godwoken/pull/932
   - fix(web3): eth_getFilterLogs should return all matched logs https://github.com/godwokenrises/godwoken/pull/947

- Enhancement:

  - chore: use TransactionDB and refactor store https://github.com/godwokenrises/godwoken/pull/903
  - chore: refactor rpc server https://github.com/godwokenrises/godwoken/pull/927
  - Improve the error code of API when executing transactions https://github.com/godwokenrises/godwoken/pull/930

## Release notes
   - Godwoken
      https://github.com/godwokenrises/godwoken/releases

  - Godwoken-web3
     https://github.com/godwokenrises/godwoken-web3/releases
  

## Changed Configs
1.  https://github.com/godwokenrises/godwoken/pull/946
    We introduced a breaking change of the config file  The consensus-related options are moved into option consensus, 
    and we put the builtin testnet and mainnet consensus into 
    the godwoken program. This change reduces the operation works of node maintainers

2023-02-21 14:57 UTC, Flouse requested changes

2023-02-21 14:57 UTC, Flouse commented on testnet_v1_1/gw-testnet_v1-config-readonly.toml
> +path = '/mnt/testnet-20230215.rocksdb'
```suggestion
path = '/mnt/store-20221008.db'
```

2023-02-21 14:57 UTC, Flouse commented on testnet_v1_1/docker-compose.yml
> +    image: ghcr.io/godwokenrises/godwoken:1.12-rc-smt-trie
```suggestion
    image: ghcr.io/godwokenrises/godwoken:v1.12.0-rc2-smt-trie
```

2023-02-21 14:57 UTC, Flouse commented on testnet_v1_1/docker-compose.yml
> +        #godwoken run -c /deploy/config.toml
```suggestion

        # Run Godwoken
        godwoken run -c /deploy/config.toml
```

2023-02-22 02:11 UTC, jjyr approved these changes

2023-02-22 03:11 UTC, Flouse approved these changes

2023-02-23 04:09 UTC, Flouse commented
The gw-readonly-node of GwScan has been upgraded to v1.12.0-rc2-smt-trie

2023-02-23 04:10 UTC, merged